### ISSUE TITLE
Add NextAuth API Route

### ISSUE THREAD

**Issue by khandrew1** [acm-ucr/bitByBit#254]
* We are converting our authentication from FirebaseAuth to NextAuth
* Add NextAuth to the project with `npm` and set up the initial API route
* Here are some resources on how to get started
    * https://next-auth.js.org/getting-started/example
    * https://next-auth.js.org/providers/google
    * https://www.youtube.com/watch?v=A5ZN--P9vXM
* Just configure the initial API route with the Google Provider

**Comment by abhijain1705** [comment]
is that open can I contribute to it?
